### ISSUE TITLE
No way to set overwrite=TRUE

### ISSUE THREAD

**Issue by noamross** [Ironholds/driver#2]
`download_file()` fails if it will overwrite a file.  Right now `...` passes arguments to GET, but it would be nice if there were a way to pass `overwrite=TRUE` to `write_disk()`.

**Comment by Ironholds** [comment]
Hmn. As I see it, we have two options:

1. ask users to pass a list of lists into ..., so you can do list(get_args = list(user_agent("foo")), write_args = list(overwrite = TRUE). This seems...brittle? But that might just be me being silly ;p.
2. In this specific case, overwrite feels like the sort of arg we should be passing out to the top level and having as a parameter in download_file - that value is then passed to write_disk(). Thoughts? Other similarly important write_disk args, in your opinion?

**Comment by noamross** [comment]
`overwrite` is the only argument in `write_disk()` other than the file path.  I say go with (2).  My personal preference is that the default be `TRUE`, which is consistent with most functions in R, though I guess Hadley made it `FALSE` for safety.

**Comment by Ironholds** [comment]
TRUE works for me! I'll patch this evening unless you want to put a quick PR in.
